all:
	cd 00_single_thread && make
	cd 01_context_save_restore && make
	cd 02_context_switch && make
	cd 03_multitasking && make
	cd 04_kernel_class && make
	cd 05_final_os && make


clean:
	cd 00_single_thread && make clean
	cd 01_context_save_restore && make clean
	cd 02_context_switch && make clean
	cd 03_multitasking && make clean
	cd 04_kernel_class && make clean
	cd 05_final_os && make clean
